"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from datetime import timedelta
from pathlib import Path
# Для чтения переменной окружения в settings.py из .env:
from environ import Env
# import environ
# Для работы блока логирования проекта:
import os




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Чтение переменной окружения в settings.py:
env = Env()
Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')      # Video 13, 3:11:40 - 1-st Lecture to Django (Intro). link: https://player.vimeo.com/video/1089675502?h=23260e4621
# config('SECRET_KEY') — просто читает строку.


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)     # default=False - выполняется только если в .env НИЧЕГО НЕТ про Дебаг.

# -----------------------------------------------------------------------------------------------------------------
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])        # Video 13, 3:13:30 - 1-st Lecture to Django (Intro). link: https://player.vimeo.com/video/1089675502?h=23260e4621
# — превращает строку 127.0.0.1,localhost в список ['127.0.0.1', 'localhost']. 8000 - PORT.
# ALLOWED_HOSTS = []         # Разрешает все хосты (НЕ использовать в продакшн)

# Для устранения ОШИБКИ из-за НЕбезопасности POST-запросов, включая формы в админке (см. .env):
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
# -----------------------------------------------------------------------------------------------------------------



# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ____  djangorestframework  ______ see Les/Video 22
    'rest_framework',
    # Аутентификация ______ 23.07.25 + 24.07.2025:
    'rest_framework.authtoken',
    # Аутентификация JWT ______ Practice 9, 24.07.2025:
    'rest_framework_simplejwt',
    # Аутентификация JWT - black list ______ Les 37, Lec 33, 25.07.2025:
    'rest_framework_simplejwt.token_blacklist',
    # ____ Для practice_21_07.md
    'django_filters',
    # ____  МОИ  ПРИЛОЖЕНИЯ  __________
    # 'les_01_begins',               # Video 13, __:__:__ - 1-st Lecture to Django (Intro). link: https://player.vimeo.com/video/1089675502?h=23260e4621
    'hw_01_first_app',
    'les_15_users',
    'hw_02_task_manager',
    'project',
    'les_18_shop',
    # ____ Для HW_06   -->  5.2.2. Подключение Swagger и ReDoc
    'drf_spectacular',
    'drf_spectacular_sidecar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Для моих приложений middleware:
    'DjangoProject_config.middleware.JWTAuthenticationMiddleware',
]

ROOT_URLCONF = 'DjangoProject_config.urls'
# ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject_config.wsgi.application'
# WSGI_APPLICATION = 'DjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if env.bool('MYSQL', default=False):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST', default="localhost"),
            'PORT': env('DB_PORT', default="3306"),
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'     # See Lec18, slide 42.

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# _____ HW_06 - Пагинация — это способ разделить большой список объектов на страницы.
# +++
# _____ 5. ДОПОЛНИТЕЛЬНО  -->  5.2.2. Подключение Swagger и ReDoc
REST_FRAMEWORK = {
    # "DEFAULT_RENDERER_CLASSES": [         # Для других браузеров, если по умолчанию не отрендерит, как в Хроме.
    #     "rest_framework.renderers.JSONRenderer",
    #     "rest_framework.renderers.BrowsableAPIRenderer",
    # ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,  # Теперь по умолчанию на всех страницах будет 5 элементов. Можно поставить 5, 20 и т.д.

    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # 'PAGE_SIZE': 10,  # Здесь PAGE_SIZE работает как 'default_limit'

    # Указываем полный путь к нашему классу!
    # 'DEFAULT_PAGINATION_CLASS': 'config.paginations.CustomCursorPagination',
    # 'PAGE_SIZE': 5,

    # Для Swagger и Redoc:
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Подключение фильтрации. См. hw_09:
    'DEFAULT_FILTER_BACKENDS': [
            "django_filters.rest_framework.DjangoFilterBackend"
        ],

    # ----------------------------------------------------------------
    # 23.07.2025 - Basic Authentication:

    'DEFAULT_AUTHENTICATION_CLASSES': [
    'rest_framework_simplejwt.authentication.JWTAuthentication',
    # 'rest_framework.authentication.TokenAuthentication',
      # Если вы хотите использовать несколько методов, добавьте их здесь.
      # Например:
    # 'rest_framework.authentication.SessionAuthentication',
    # 'rest_framework.authentication.BasicAuthentication',
        ],

    # 23.07.2025 - Permissions:
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # ----------------------------------------------------------------

}



# Lesson 33 "Lec 30: JWT-аутентификация", 23.07.2025 - Basic Authentication:
# +++
# Аутентификация JWT ______ Practice 9, 24.07.2025:
SIMPLE_JWT = {
    # Время жизни access токена (короткое):
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    # Время жизни refresh токена (длинное):
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),
    # Можно добавить и другие настройки, например, для токенов одноразового использования

    # Включаем ротацию refresh токенов для повышения безопасности:
    'ROTATE_REFRESH_TOKENS': True,
    # Добавляем старый refresh токен в черный список после его использования:
    'BLACKLIST_AFTER_ROTATION': True,
    # Указываем тип заголовка авторизации:
    'AUTH_HEADER_TYPES': ('Bearer',),
}



# _____ HW_06 --->
# _____ 5. ДОПОЛНИТЕЛЬНО  -->  5.2.2. Подключение Swagger и ReDoc
# http://drf-spectacular.readthedocs.io/en/latest/settings.html
SPECTACULAR_SETTINGS = {
    'TITLE': 'Task Manager API',
    'DESCRIPTION': 'API для управления задачами и подзадачами',
    'VERSION': '1.0.0',
}

SPECTACULAR_DEFAULTS = {
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],  # Permissions for schema UI views
    # 'SERVE_AUTHENTICATION': None,  # Authentication class for schema UI views; None to use DRF default
}




# _____ HW_11  -  Задание 2.  Логирования работы включенного сервера:

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    # Из примера Бандыло - filters (для чего нужен - НЕ понятно):
    'filters': {
            'require_debug_true': {
                '()': 'django.utils.log.RequireDebugTrue',
            }
        },

    'handlers': {
        'console': {  # Логирование сервера в консоль
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },

        'http_file': {  # Логирование HTTP-запросов
            'level': 'DEBUG',
            # 'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'http_logs.log'),    # http_logs.log - Файл для логов
            'formatter': 'verbose',
        },

        'db_file': {  # Логирование SQL-запросов
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'db_logs.log'),
            'formatter': 'verbose',
        },
    },

    'loggers': {
        'django': {  # Основные логи Django, в консоль
            'handlers': ['console', 'http_file'],       # Куда выводить и записывать логи.
            'level': 'INFO',
        },

        'django.server': {  # Сервер (runserver)
            'handlers': ['console', 'http_file'],       # Куда выводить и записывать логи.
            'level': 'INFO',
            'propagate': False,
        },

        'django.request': {  # HTTP-запросы
            'handlers': ['http_file'],       # Куда выводить и записывать логи.
            'level': 'DEBUG',
            # 'level': 'INFO',
            'propagate': False,
        },

        'django.db.backends': {  # SQL-запросы
            'handlers': ['db_file'],     # Куда отправлять логи. Пока закомментирую эту опцию - 'console',
            'level': 'DEBUG',            # Уровень логирования.
            'propagate': False,
        },
    }
}
# 24.07.2025 - Pr 10: Задание 3. Добавление эндпоинт для статистики. Часть 1
AUTH_USER_MODEL = env('AUTH_USER_MODEL', default='auth.User')



# ---------------------------- НЕ ЗНАЮ пока, для чего - разберусь позже -------------
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

