# Generated by Django 5.2.1 on 2025-07-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('les_18_shop', '0002_product_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
    ]
