# Generated by Django 5.2.1 on 2025-07-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('les_18_shop', '0004_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'order_date', 'ordering': ['-order_date'], 'permissions': [('can_view_order_statistics', 'Can view order statistics')]},
        ),
    ]
