# Generated by Django 5.2.1 on 2025-06-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('py', 'Python'), ('c', 'C'), ('c#', 'C#'), ('cpp', 'C++'), ('java', 'Java')])),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('team_lead', 'Team Lead')])),
                ('projects', models.ManyToManyField(related_name='developers', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('q&a', 'Q&A'), ('design', 'Design'), ('devops', 'DevOPS')])),
                ('description', models.CharField(max_length=255)),
                ('projects', models.ManyToManyField(related_name='tags', to='project.project')),
            ],
        ),
    ]
