# Generated by Django 5.2.1 on 2025-06-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='description',
        ),
    ]
