# Generated by Django 5.2.1 on 2025-06-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_task_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'description')},
        ),
    ]
