# Generated by Django 5.2.1 on 2025-06-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_task_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'description')},
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('name__icontains', 'project')), name='project_name__icontains'),
        ),
    ]
