# Generated by Django 5.2.1 on 2025-06-09 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категория выполнения', max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, error_messages={'unique_for_date': 'Это название уже используется для сегодняшней даты. Введите другое название.'}, help_text='Введите название задачи, иначе будет присвоено название по умолчанию Task+Number', max_length=50, unique_for_date='publish_date', validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Done', 'Done')], verbose_name='Статус задачи')),
                ('deadline', models.DateTimeField(help_text='Введите дату и время дедлайна.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('categories', models.ManyToManyField(help_text='Категории, к которым относится задача', related_name='tasks', to='hw_02_task_manager.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Отдельная часть основной задачи', max_length=50, verbose_name='Название подзадачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание подзадачи')),
                ('status', models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Done', 'Done')], verbose_name='Статус подзадачи')),
                ('deadline', models.DateTimeField(help_text='Введите дату и время дедлайна для этой подзадачи.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания подзадачи')),
                ('task', models.ForeignKey(help_text='Основная задача', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='hw_02_task_manager.task')),
            ],
        ),
    ]
