# Generated by Django 5.2.1 on 2025-08-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_02_task_manager', '0006_subtask_owner_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_notified_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
