# Generated by Django 5.2.1 on 2025-06-09 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('les_15_users', '0004_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(140)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('PT', 'Portugal'), ('ES', 'Spain'), ('MV', 'Maldives'), ('DE', 'Germany')], default='DE', help_text='Where are you born?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=70, verbose_name='Family name'),
        ),
    ]
