# Generated by Django 5.2.1 on 2025-06-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('les_15_users', '0006_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('actors', models.ManyToManyField(related_name='movies', to='les_15_users.actor')),
            ],
        ),
    ]
